name: flutter_boilerplate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #  make request for servers
  http_interceptor: ^2.0.0
  http: ^1.3.0
  #  date library
  intl: ^0.19.0
  #  GETX state management
  get: ^4.7.2

  #  launch url in browsers
  url_launcher: ^6.3.1

  #  for check internet
  connectivity_plus: ^6.1.3

  #  storage
  shared_preferences: ^2.5.2
  hive: ^2.2.3

  #  permission
  permission_handler: ^11.4.0
  path_provider: ^2.1.5

  #  share content
  share_plus: ^10.1.4

  # firebase
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  firebase_analytics: ^11.4.3
  firebase_remote_config: ^5.4.1

  #  Device Specific
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.0
  android_id: ^0.4.0
  wakelock_plus: 1.2.11

  #  notification
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
